/**
 * @file Docs view for the OpenAI embeddings debug scenario.
 */

export type Doc = {
  id: number;
  title: string;
  content: string;
  category: string;
  tags: string[];
  author: string;
  year: number;
};

export const DOCS: Doc[] = [
  {
    id: 1,
    title: "はじめてのHNSW: 近似近傍探索の仕組み",
    content:
      "HNSWグラフのレイヤ構造やefSearch/efConstructionの直感的な意味、実務でのパラメータ選定のポイントを解説します。",
    category: "tech",
    tags: ["ann", "hnsw", "vector"],
    author: "Sato",
    year: 2023,
  },
  {
    id: 2,
    title: "生成AI活用事例まとめ 2025春",
    content: "社内検索、FAQボット、要約パイプラインなど、生成AIの実案件で得られた学びとベストプラクティスを紹介。",
    category: "tech",
    tags: ["genai", "llm", "embeddings"],
    author: "Kobayashi",
    year: 2025,
  },
  {
    id: 3,
    title: "平日ラクうま！10分パスタ",
    content: "ツナ缶とトマトで作る簡単パスタ。包丁いらずで、在宅ワークの昼食にもぴったり。",
    category: "food",
    tags: ["recipe", "pasta", "quick"],
    author: "Tanaka",
    year: 2022,
  },
  {
    id: 4,
    title: "週末トレッキング入門: 高尾山コース",
    content: "アクセス良好で初心者にも優しいコース。装備、ルート、混雑回避のコツを紹介します。",
    category: "travel",
    tags: ["outdoor", "hiking"],
    author: "Suzuki",
    year: 2021,
  },
  {
    id: 5,
    title: "金融データで学ぶ相関と分散",
    content: "株価の相関・分散・共分散行列の基礎と、ポートフォリオ分散の直感的な理解。",
    category: "finance",
    tags: ["statistics", "portfolio"],
    author: "Yamada",
    year: 2020,
  },
  {
    id: 6,
    title: "スポーツ科学: 有酸素運動とVO2max",
    content: "VO2maxの測定方法とトレーニング計画、心拍数ゾーン管理の基本をわかりやすく解説。",
    category: "sports",
    tags: ["training", "health"],
    author: "Kato",
    year: 2024,
  },
  {
    id: 7,
    title: "はじめての水彩画: グラデーションとにじみ",
    content: "水彩ならではのにじみ効果と色の重ね方、筆と紙の選び方を初心者向けにまとめました。",
    category: "art",
    tags: ["watercolor", "beginner"],
    author: "Ito",
    year: 2019,
  },
  {
    id: 8,
    title: "睡眠の質を高めるナイトルーティン",
    content: "寝る90分前の入浴、ブルーライト対策、就寝前ストレッチで深い眠りを実現。",
    category: "health",
    tags: ["sleep", "habit"],
    author: "Nakajima",
    year: 2023,
  },
  {
    id: 9,
    title: "実装で学ぶビットマップインデックス",
    content: "属性の存在判定や複合条件のAND/ORを高速に処理するためのビットマップ戦略を実装解説。",
    category: "tech",
    tags: ["bitmap", "index"],
    author: "Sasaki",
    year: 2024,
  },
  {
    id: 10,
    title: "短編レビュー: 夕暮れの図書室",
    content: "静かな学校の図書室で出会う、ささやかな対話と小さな勇気を描いた短編の感想。",
    category: "literature",
    tags: ["novel", "review"],
    author: "Aoki",
    year: 2022,
  },
  {
    id: 11,
    title: "冷蔵庫の奥に眠る謎のタッパー",
    content:
      "半年以上前のカレーらしきものが発掘されたが、開ける勇気はない。冷蔵庫の奥は時空の歪み。なぜ人はタッパーを奥に押し込んでしまうのか。",
    category: "daily",
    tags: ["refrigerator", "mystery"],
    author: "Mori",
    year: 2025,
  },
  {
    id: 12,
    title: "なぜか消える靴下の片方の真実",
    content:
      "洗濯機の中で靴下が片方だけ消える現象について、物理学的・哲学的・オカルト的に考察。結論は出ないが、靴下の片方はどこへ行くのか。",
    category: "trivia",
    tags: ["socks", "mystery"],
    author: "Yoshida",
    year: 2025,
  },
  {
    id: 13,
    title: "深夜のポテチはなぜ美味いのか",
    content:
      "健康に悪いと分かっていても、深夜に食べるポテチの背徳感と幸福感について熱く語る。袋を開ける音が静寂に響く瞬間の快感。",
    category: "food",
    tags: ["snack", "night"],
    author: "Fujimoto",
    year: 2025,
  },
  {
    id: 14,
    title: "カラスは本当に人の顔を覚えるのか?",
    content:
      "都市伝説として語られるカラスの知能。実験と観察から分かった意外な事実と、カラスとの心理戦。カラスに睨まれた話。",
    category: "animal",
    tags: ["crow", "urbanlegend"],
    author: "Kishida",
    year: 2024,
  },
  {
    id: 15,
    title: "エレベーターのボタンを連打する心理",
    content:
      "早く来てほしい時に無意味に連打してしまう理由を、心理学と行動経済学の観点から解説。連打しても早くならないのに、なぜかやってしまう。",
    category: "psychology",
    tags: ["elevator", "habit"],
    author: "Ono",
    year: 2023,
  },
  {
    id: 16,
    title: "ペン回しの奥深き世界",
    content:
      "授業中に始まったペン回しが、世界大会まで存在する競技に発展した歴史と技の数々。ペン回しの達人の手元動画を見て驚愕。",
    category: "hobby",
    tags: ["pen", "trick"],
    author: "Matsuda",
    year: 2022,
  },
  {
    id: 17,
    title: "トイレの個室で考える人生",
    content:
      "静かな個室は最高の思索空間。過去の失敗や将来の夢、くだらない悩みまでトイレで考えがち。トイレ哲学のすすめ。",
    category: "philosophy",
    tags: ["toilet", "thinking"],
    author: "Sakai",
    year: 2025,
  },
  {
    id: 18,
    title: "猫の肉球はなぜぷにぷになのか",
    content: "猫の肉球の構造と進化、触った時の癒し効果について科学的に無理やり解説。肉球を触ると幸せになる理由。",
    category: "animal",
    tags: ["cat", "science"],
    author: "Nakamura",
    year: 2023,
  },
  {
    id: 19,
    title: "意味不明な夢の話",
    content:
      "空を飛ぶ夢、歯が抜ける夢、なぜか追いかけられる夢など、意味不明な夢の体験談とその解釈。夢占いは信じるべきか。",
    category: "dream",
    tags: ["sleep", "story"],
    author: "Takagi",
    year: 2024,
  },
  {
    id: 20,
    title: "自販機の下に落ちてる謎の小銭",
    content: "なぜか自販機の下には小銭が落ちている。拾うべきか、見なかったことにするべきか。哲学的考察。小銭の行方。",
    category: "daily",
    tags: ["vendingmachine", "coin"],
    author: "Ueda",
    year: 2025,
  },
  {
    id: 21,
    title: "カップ麺の待ち時間を短縮する方法はあるのか?",
    content: "3分待てない人のための、カップ麺の待ち時間短縮テクニックと失敗談。熱湯を使う意味。",
    category: "food",
    tags: ["instant", "hack"],
    author: "Kawamura",
    year: 2022,
  },
  {
    id: 22,
    title: "謎のUSBメモリの中身を覗いてみた",
    content:
      "机の奥から出てきた正体不明のUSBメモリ。中身は昔の卒論と謎の画像ファイルだった。思い出と謎が詰まっていた。",
    category: "tech",
    tags: ["usb", "nostalgia"],
    author: "Hayashi",
    year: 2021,
  },
  {
    id: 23,
    title: "カラオケで絶対に歌わない曲ランキング",
    content: "盛り上がらない、キーが高すぎる、そもそも誰も知らない…カラオケで避けられがちな曲を独断と偏見で紹介。",
    category: "music",
    tags: ["karaoke", "ranking"],
    author: "Shimizu",
    year: 2023,
  },
  {
    id: 24,
    title: "謎の町内会イベントに参加してみた",
    content: "町内会のイベントに参加したら、謎のゲームと謎の景品で盛り上がった。地域コミュニティの奥深さ。",
    category: "community",
    tags: ["event", "local"],
    author: "Okada",
    year: 2024,
  },
  {
    id: 25,
    title: "エアコンのリモコンがどこかに消える現象",
    content:
      "使いたい時に限って見つからないエアコンのリモコン。家族全員で大捜索した結果、冷蔵庫の上にあった。リモコンの旅。",
    category: "daily",
    tags: ["aircon", "lost"],
    author: "Miyamoto",
    year: 2025,
  },
  {
    id: 26,
    title: "意味のない会議で考えていたこと",
    content: "会議中にふと考えてしまう、今日の晩ご飯や週末の予定。会議の意味とは何か。会議哲学。",
    category: "work",
    tags: ["meeting", "thought"],
    author: "Nakano",
    year: 2023,
  },
  {
    id: 27,
    title: "謎の植物を育ててみた結果",
    content: "ホームセンターで買った正体不明の苗。育ててみたら、予想外の花が咲いた。植物のサプライズ。",
    category: "hobby",
    tags: ["plant", "experiment"],
    author: "Kondo",
    year: 2022,
  },
  {
    id: 28,
    title: "コンビニの新商品を全部買ってみた",
    content: "新発売のスイーツやドリンクを片っ端から買ってみた感想。意外な当たりと、微妙なハズレ。コンビニ探検記。",
    category: "food",
    tags: ["convenience", "review"],
    author: "Saito",
    year: 2025,
  },
  {
    id: 29,
    title: "謎のBGMが流れるスーパー",
    content: "スーパーで流れる謎のBGM。誰が選曲しているのか、なぜか耳に残る理由を考察。スーパーの音楽事情。",
    category: "music",
    tags: ["supermarket", "bgm"],
    author: "Yamashita",
    year: 2024,
  },
  {
    id: 30,
    title: "意味不明なLINEスタンプの使い道",
    content:
      "友達から送られてきた意味不明なLINEスタンプ。どう返すべきか悩んだ結果、同じく意味不明なスタンプで返した。LINEスタンプの無限ループ。",
    category: "communication",
    tags: ["line", "stamp"],
    author: "Morita",
    year: 2025,
  },
  {
    id: 31,
    title: "台風12号、関東に接近 午後から激しい雨に警戒",
    content:
      "気象庁によると、台風12号は18日午後に関東地方へ最接近する見込み。交通機関への影響や土砂災害に注意が必要。最新の進路予報と各地の状況を速報。",
    category: "news",
    tags: ["weather", "typhoon"],
    author: "Yahoo編集部",
    year: 2025,
  },
  {
    id: 32,
    title: "人気俳優・佐藤健さん、電撃結婚を発表",
    content:
      "俳優の佐藤健さん（36）が自身のSNSで結婚を発表。お相手は一般女性。ファンや芸能界から祝福の声が多数寄せられている。",
    category: "entertainment",
    tags: ["actor", "marriage"],
    author: "Yahoo芸能",
    year: 2025,
  },
  {
    id: 33,
    title: "都内で謎の爆発音、警察が調査中",
    content:
      "18日午前、東京都内の住宅街で爆発音が複数回確認され、住民から通報が相次いだ。警察は現場周辺を封鎖し、原因を調査している。怪我人は今のところ確認されていない。",
    category: "news",
    tags: ["incident", "tokyo"],
    author: "Yahoo社会",
    year: 2025,
  },
  {
    id: 34,
    title: "大谷翔平、今季30号ホームラン達成",
    content:
      "米メジャーリーグ・エンゼルスの大谷翔平選手が今季30号ホームランを記録。日本人選手として史上初の快挙。現地ファンも大歓声。",
    category: "sports",
    tags: ["baseball", "otani"],
    author: "Yahooスポーツ",
    year: 2025,
  },
  {
    id: 35,
    title: "新型iPhone、9月に発表か 噂される新機能まとめ",
    content: "Appleが9月に新型iPhoneを発表するとの情報。噂される新機能やデザイン、価格予想などを徹底解説。",
    category: "tech",
    tags: ["iphone", "apple"],
    author: "Yahoo IT",
    year: 2025,
  },
  {
    id: 36,
    title: "コンビニおにぎり値上げ、消費者に広がる困惑",
    content:
      "大手コンビニ各社が原材料高騰を受けておにぎりの価格を一斉に値上げ。SNSでは『昼ごはんどうしよう』と嘆く声も。",
    category: "economy",
    tags: ["convenience", "price"],
    author: "Yahoo経済",
    year: 2025,
  },
  {
    id: 37,
    title: "渋谷駅前で巨大アヒル出現、SNSで話題に",
    content:
      "18日朝、渋谷駅前に巨大なアヒルのオブジェが登場し、通勤客や観光客が写真撮影。SNSでは『謎すぎる』『かわいい』と話題沸騰。",
    category: "news",
    tags: ["shibuya", "event"],
    author: "Yahoo編集部",
    year: 2025,
  },
  {
    id: 38,
    title: "ペンギン大好きクラブ特集：まぜぺんのふしぎな日常",
    content:
      "ペンギン大好きクラブの人気者・まぜぺんは、今日も氷の上でみんなとごちゃまぜお昼寝。小さなペンギンたちが集まって、まぜぺんの背中に乗ったり、すべって遊んだり。時々おやつの魚を分け合う姿がとっても可愛い！まぜぺんの得意技は、みんなをぎゅっと集めてふわふわ団子になること。見ているだけで癒される、ほっこりエピソード満載です。",
    category: "animal",
    tags: ["penguin", "club", "cute", "mazepen"],
    author: "ペンギン大好きクラブ編集部",
    year: 2025,
  },
  {
    id: 39,
    title: "まぜぺんの朝ごはんタイムは大騒ぎ！",
    content:
      "マゼランペンギンたちが朝ごはんの魚をもらうと、みんなでピョンピョン跳ねて大はしゃぎ。まぜぺんは一番小さいけど、ちゃっかり一番美味しい魚をゲットする名人。みんなで分け合う姿がとても微笑ましいです。",
    category: "animal",
    tags: ["penguin", "mazepen", "cute", "breakfast"],
    author: "ペンギン大好きクラブ編集部",
    year: 2025,
  },
  {
    id: 40,
    title: "まぜぺんのすべり台チャレンジ！",
    content:
      "氷のすべり台を作ったら、まぜぺんが一番乗りでツルツルすべって大成功。後ろから他のペンギンたちも続いて、みんなで大行列。すべり終わった後はみんなで拍手喝采！",
    category: "animal",
    tags: ["penguin", "mazepen", "slide", "fun"],
    author: "ペンギン大好きクラブ編集部",
    year: 2025,
  },
  {
    id: 41,
    title: "まぜぺんのふわふわお昼寝団子",
    content:
      "お昼寝タイムになると、まぜぺんを中心にみんながぎゅっと集まって団子状態。ふわふわの羽毛に包まれて、みんな幸せそうな顔でスヤスヤ。見ているだけで癒されます。",
    category: "animal",
    tags: ["penguin", "mazepen", "nap", "cute"],
    author: "ペンギン大好きクラブ編集部",
    year: 2025,
  },
  {
    id: 42,
    title: "まぜぺんの初めての泳ぎレッスン",
    content:
      "まぜぺんは泳ぎがちょっと苦手。でも今日はお兄さんペンギンに教えてもらって、勇気を出してプールにジャンプ！みんなで応援して、無事に泳げるようになりました。",
    category: "animal",
    tags: ["penguin", "mazepen", "swim", "lesson"],
    author: "ペンギン大好きクラブ編集部",
    year: 2025,
  },
  {
    id: 43,
    title: "まぜぺんの誕生日パーティー開催！",
    content:
      "今日はまぜぺんの誕生日。みんなで魚ケーキを作ってお祝い。まぜぺんはちょっと照れながらも、みんなに囲まれてとっても嬉しそう。記念写真もバッチリ！",
    category: "animal",
    tags: ["penguin", "mazepen", "birthday", "party"],
    author: "ペンギン大好きクラブ編集部",
    year: 2025,
  },
  {
    id: 44,
    title: "まぜぺんのかくれんぼ名人伝説",
    content:
      "まぜぺんはかくれんぼが大得意。岩陰や氷の下に隠れて、みんなが探してもなかなか見つからない。見つかった時のニコニコ顔がとってもキュート！",
    category: "animal",
    tags: ["penguin", "mazepen", "hideandseek", "cute"],
    author: "ペンギン大好きクラブ編集部",
    year: 2025,
  },
  {
    id: 45,
    title: "まぜぺんの雨の日の過ごし方",
    content:
      "雨の日はみんなで小屋の中でまったりタイム。まぜぺんはみんなの真ん中で、ふわふわの羽毛を広げてみんなを包み込む。雨音を聞きながらのんびり過ごすのが大好き。",
    category: "animal",
    tags: ["penguin", "mazepen", "rainyday", "relax"],
    author: "ペンギン大好きクラブ編集部",
    year: 2025,
  },
  {
    id: 46,
    title: "まぜぺんのいたずら大作戦！",
    content:
      "まぜぺんは時々いたずら好き。みんなの魚をこっそり隠したり、氷の上で転がってみんなを笑わせたり。いたずらがバレると、みんなで大笑い！",
    category: "animal",
    tags: ["penguin", "mazepen", "prank", "fun"],
    author: "ペンギン大好きクラブ編集部",
    year: 2025,
  },
  {
    id: 47,
    title: "まぜぺんの星空観察会",
    content:
      "夜になると、まぜぺんたちはみんなで外に出て星空を眺めます。まぜぺんは一番星を見つけるのが得意。みんなで静かに星を見ながら、夢を語り合う素敵な時間。",
    category: "animal",
    tags: ["penguin", "mazepen", "star", "night"],
    author: "ペンギン大好きクラブ編集部",
    year: 2025,
  },
  {
    id: 48,
    title: "アルゼンチン・プンタトンボのマゼランペンギン群生地",
    content:
      "アルゼンチン南部のプンタトンボは、世界最大級のマゼランペンギンの繁殖地。毎年9月から4月にかけて、数十万羽のペンギンが集まり、巣作りや子育てを行います。自然保護区として管理されており、観察デッキからペンギンたちの生活を間近で見ることができます。生態系や保護活動についても詳しく解説。",
    category: "animal",
    tags: ["penguin", "mazepen", "argentina", "colony"],
    author: "ペンギン大好きクラブ編集部",
    year: 2025,
  },
  {
    id: 49,
    title: "フォークランド諸島のマゼランペンギンたち",
    content:
      "南大西洋に浮かぶフォークランド諸島は、マゼランペンギンの重要な生息地のひとつ。広大な草原や海岸で、ペンギンたちが自由に暮らしています。現地ではエコツーリズムも盛んで、ペンギンの保護と地域経済の両立が進められています。島の自然環境やペンギンの季節ごとの行動についても紹介。",
    category: "animal",
    tags: ["penguin", "mazepen", "falkland", "nature"],
    author: "ペンギン大好きクラブ編集部",
    year: 2025,
  },
  {
    id: 50,
    title: "フォークランド紛争とは何だったのか",
    content:
      "1982年、イギリスとアルゼンチンの間で勃発したフォークランド紛争。南大西洋の小さな島々を巡る戦いは、両国の歴史や国民感情に大きな影響を与えました。戦争の経緯や国際社会の反応、現在の領有権問題について解説します。",
    category: "history",
    tags: ["falkland", "war", "argentina", "uk"],
    author: "歴史研究会",
    year: 2025,
  },
  {
    id: 51,
    title: "フォークランド紛争の記憶：アルゼンチン側の視点",
    content:
      "アルゼンチンではフォークランド紛争は『マルビナス戦争』として記憶されています。退役軍人や遺族の証言、戦後の社会への影響、教育現場での扱いなど、アルゼンチン側から見た紛争の意味を掘り下げます。",
    category: "history",
    tags: ["falkland", "malvinas", "argentina", "memory"],
    author: "歴史研究会",
    year: 2025,
  },
  {
    id: 52,
    title: "ブエノス・アイレスの街歩きガイド",
    content:
      "アルゼンチンの首都ブエノス・アイレスは、ヨーロッパ風の建築と南米らしい活気が融合した魅力的な都市。カフェ文化、タンゴの発祥地、歴史的な広場や美術館など、見どころをたっぷり紹介します。",
    category: "travel",
    tags: ["buenosaires", "argentina", "city", "guide"],
    author: "南米探訪編集部",
    year: 2025,
  },
  {
    id: 53,
    title: "ボルヘスの文学世界：迷宮と夢の物語",
    content:
      "ホルヘ・ルイス・ボルヘスは、アルゼンチンを代表する作家。『伝奇集』や『砂の本』など、迷宮や夢、無限をテーマにした独特の短編が世界中で愛されています。彼の作品の魅力と影響を解説。",
    category: "literature",
    tags: ["borges", "argentina", "novel", "philosophy"],
    author: "文学サロン",
    year: 2025,
  },
  {
    id: 54,
    title: "ピアソラとタンゴ革命",
    content:
      "アストル・ピアソラは、伝統的なタンゴにジャズやクラシックの要素を融合し、新しい音楽ジャンル『ヌエボ・タンゴ』を生み出しました。代表曲『リベルタンゴ』や彼の生涯、世界的な評価について紹介します。",
    category: "music",
    tags: ["piazzolla", "tango", "argentina", "music"],
    author: "音楽探究会",
    year: 2025,
  },
  {
    id: 55,
    title: "イギリスの歴史と文化：ロンドンから湖水地方まで",
    content:
      "イギリスは長い歴史と豊かな文化を持つ国。ロンドンの博物館や劇場、湖水地方の自然、伝統的なパブ文化など、イギリスの魅力を幅広く紹介します。",
    category: "travel",
    tags: ["uk", "england", "culture", "history"],
    author: "ヨーロッパ紀行編集部",
    year: 2025,
  },
  {
    id: 56,
    title: "イギリス文学の巨人たち：シェイクスピアから現代作家まで",
    content:
      "イギリス文学は世界に多大な影響を与えてきました。シェイクスピア、ジェーン・オースティン、J.K.ローリングなど、代表的な作家とその作品、文学史の流れを解説します。",
    category: "literature",
    tags: ["uk", "literature", "shakespeare", "rowling"],
    author: "文学サロン",
    year: 2025,
  },
  {
    id: 58,
    title: "アインシュタインと相対性理論",
    content:
      "アルベルト・アインシュタインは20世紀最大の物理学者。特殊・一般相対性理論を提唱し、宇宙観を一変させた。ノーベル賞も受賞。",
    category: "science",
    tags: ["einstein", "physics", "relativity"],
    author: "科学サロン",
    year: 2025,
  },
  {
    id: 59,
    title: "アマゾン熱帯雨林の生態系",
    content:
      "南米アマゾンは世界最大の熱帯雨林。多様な動植物が生息し、地球の酸素供給にも重要な役割を果たす。近年は伐採や気候変動が問題に。",
    category: "nature",
    tags: ["amazon", "rainforest", "ecosystem"],
    author: "自然探究会",
    year: 2025,
  },
  {
    id: 60,
    title: "ニューヨーク：世界都市の歴史と文化",
    content:
      "アメリカ・ニューヨークは移民の街として発展し、金融・芸術・ファッションの中心地。自由の女神やセントラルパークなど観光名所も多い。",
    category: "travel",
    tags: ["newyork", "usa", "city"],
    author: "都市ガイド編集部",
    year: 2025,
  },
  {
    id: 61,
    title: "イヌイットの暮らしと文化",
    content:
      "北極圏に住むイヌイットは、氷と雪の世界で独自の文化を築いてきた。狩猟や伝統的な住居イグルー、現代の変化について紹介。",
    category: "culture",
    tags: ["inuit", "arctic", "tradition"],
    author: "民族学会",
    year: 2025,
  },
  {
    id: 62,
    title: "マチュピチュ：インカ帝国の空中都市",
    content:
      "ペルーのマチュピチュは、標高2400mの山中に築かれたインカ帝国の遺跡。世界遺産にも登録され、謎多き建築技術が注目される。",
    category: "history",
    tags: ["machupicchu", "inca", "peru"],
    author: "世界史研究会",
    year: 2025,
  },
  {
    id: 63,
    title: "アフリカゾウの社会構造",
    content:
      "アフリカゾウは家族単位で群れを作り、メスがリーダーとなる。長距離移動や水場の記憶力、象同士のコミュニケーションも高度。",
    category: "animal",
    tags: ["elephant", "africa", "social"],
    author: "動物百科編集部",
    year: 2025,
  },
  {
    id: 64,
    title: "ローマ帝国の興亡",
    content:
      "ローマ帝国は紀元前27年から西暦476年まで続いた巨大国家。共和政から帝政への移行、五賢帝時代、滅亡までの歴史を解説。",
    category: "history",
    tags: ["rome", "empire", "ancient"],
    author: "世界史研究会",
    year: 2025,
  },
  {
    id: 65,
    title: "パンダの生態と保護活動",
    content:
      "ジャイアントパンダは中国固有の動物。竹を主食とし、繁殖が難しいため絶滅危惧種。中国や世界各地で保護活動が進められている。",
    category: "animal",
    tags: ["panda", "china", "conservation"],
    author: "動物百科編集部",
    year: 2025,
  },
  {
    id: 66,
    title: "インターネットの歴史と発展",
    content:
      "インターネットは1960年代の軍事技術ARPANETから始まり、現在は世界中で情報通信の基盤となっている。技術革新と社会への影響を解説。",
    category: "tech",
    tags: ["internet", "history", "technology"],
    author: "IT百科編集部",
    year: 2025,
  },
  {
    id: 67,
    title: "モナリザ：レオナルド・ダ・ヴィンチの傑作",
    content:
      "モナリザはイタリアの芸術家レオナルド・ダ・ヴィンチによる肖像画。微笑みの謎や絵画技法、ルーブル美術館での展示について紹介。",
    category: "art",
    tags: ["monalisa", "davinci", "painting"],
    author: "美術探究会",
    year: 2025,
  },
  {
    id: 68,
    title: "アポロ計画と人類初の月面着陸",
    content:
      "1969年、アメリカのアポロ11号が人類初の月面着陸に成功。ニール・アームストロング船長の『小さな一歩』は歴史的名言。",
    category: "science",
    tags: ["apollo", "moon", "space"],
    author: "宇宙研究会",
    year: 2025,
  },
  {
    id: 69,
    title: "フランス革命と近代社会の誕生",
    content:
      "1789年に始まったフランス革命は、王政の終焉と市民社会の誕生をもたらした。人権宣言やナポレオンの台頭など、世界史に大きな影響。",
    category: "history",
    tags: ["france", "revolution", "modern"],
    author: "世界史研究会",
    year: 2025,
  },
  {
    id: 70,
    title: "サハラ砂漠の地理と気候",
    content:
      "サハラ砂漠はアフリカ北部に広がる世界最大の砂漠。極端な乾燥気候と多様な生態系、遊牧民の暮らしについて解説。",
    category: "nature",
    tags: ["sahara", "desert", "africa"],
    author: "自然探究会",
    year: 2025,
  },
  {
    id: 71,
    title: "マリー・キュリーと放射線の発見",
    content:
      "マリー・キュリーはポーランド出身の科学者。ラジウムとポロニウムを発見し、ノーベル賞を2度受賞。放射線研究の先駆者。",
    category: "science",
    tags: ["curie", "radiation", "nobel"],
    author: "科学サロン",
    year: 2025,
  },
  {
    id: 72,
    title: "オーストラリアのコアラとユーカリの森",
    content:
      "コアラはオーストラリア固有の動物。ユーカリの葉を主食とし、森の減少が生息数に影響。保護活動も進められている。",
    category: "animal",
    tags: ["koala", "australia", "forest"],
    author: "動物百科編集部",
    year: 2025,
  },
  {
    id: 73,
    title: "スペインのガウディ建築：サグラダ・ファミリア",
    content:
      "アントニ・ガウディはスペインの建築家。サグラダ・ファミリアは未完の大聖堂として有名で、独特のデザインが世界中から注目される。",
    category: "art",
    tags: ["gaudi", "spain", "architecture"],
    author: "美術探究会",
    year: 2025,
  },
  {
    id: 74,
    title: "アマデウス・モーツァルトの音楽と生涯",
    content: "モーツァルトはオーストリアの作曲家。交響曲やオペラなど多くの名曲を残し、天才音楽家として知られる。",
    category: "music",
    tags: ["mozart", "austria", "composer"],
    author: "音楽探究会",
    year: 2025,
  },
  {
    id: 75,
    title: "アメリカ独立戦争と建国の歴史",
    content:
      "1775年から1783年にかけて、アメリカ13植民地がイギリスから独立を勝ち取った戦争。ジョージ・ワシントンの指導や独立宣言が有名。",
    category: "history",
    tags: ["usa", "independence", "war"],
    author: "世界史研究会",
    year: 2025,
  },
  {
    id: 76,
    title: "北極のオーロラ現象",
    content: "オーロラは地球の磁場と太陽風が作用して生じる美しい光のカーテン。北極圏や南極圏で観察される自然現象。",
    category: "nature",
    tags: ["aurora", "arctic", "phenomenon"],
    author: "自然探究会",
    year: 2025,
  },
  {
    id: 77,
    title: "アジアの稲作文化と歴史",
    content: "アジアでは古代から稲作が盛ん。日本・中国・東南アジアの農業技術や食文化、社会への影響について解説。",
    category: "culture",
    tags: ["asia", "rice", "agriculture"],
    author: "民族学会",
    year: 2025,
  },
  {
    id: 78,
    title: "ガリレオ・ガリレイと近代科学の夜明け",
    content: "ガリレオはイタリアの物理学者・天文学者。望遠鏡による天体観測や、地動説の提唱で科学革命を牽引した。",
    category: "science",
    tags: ["galileo", "astronomy", "science"],
    author: "科学サロン",
    year: 2025,
  },
  {
    id: 79,
    title: "アフリカのサバンナと野生動物",
    content:
      "サバンナは広大な草原地帯で、ライオン・キリン・シマウマなど多様な動物が生息。乾季と雨季の生態系変化も特徴。",
    category: "nature",
    tags: ["africa", "savanna", "wildlife"],
    author: "自然探究会",
    year: 2025,
  },
  {
    id: 80,
    title: "ピカソと20世紀美術の革新",
    content:
      "パブロ・ピカソはスペイン出身の画家。キュビズムを創始し、20世紀美術に革命をもたらした。代表作『ゲルニカ』など。",
    category: "art",
    tags: ["picasso", "cubism", "spain"],
    author: "美術探究会",
    year: 2025,
  },
  {
    id: 81,
    title: "南極大陸の探検史",
    content:
      "南極大陸は19世紀以降、数々の探検家によって踏破された。アムンゼンやスコットの遠征、現代の科学基地についても紹介。",
    category: "history",
    tags: ["antarctica", "exploration", "science"],
    author: "世界史研究会",
    year: 2025,
  },
  {
    id: 82,
    title: "日本の浮世絵と江戸文化",
    content: "浮世絵は江戸時代の庶民文化を描いた版画。葛飾北斎や歌川広重などの作品が世界的に評価されている。",
    category: "art",
    tags: ["ukiyoe", "japan", "edo"],
    author: "美術探究会",
    year: 2025,
  },
  {
    id: 83,
    title: "アメリカの国立公園と自然保護",
    content: "アメリカにはイエローストーンやグランドキャニオンなど多くの国立公園があり、自然保護と観光が両立している。",
    category: "nature",
    tags: ["usa", "nationalpark", "conservation"],
    author: "自然探究会",
    year: 2025,
  },
  {
    id: 84,
    title: "イタリアのルネサンス美術",
    content:
      "ルネサンス期のイタリアでは、ダ・ヴィンチ、ミケランジェロ、ラファエロなど多くの芸術家が活躍。美術・建築・思想の革新が起きた。",
    category: "art",
    tags: ["renaissance", "italy", "art"],
    author: "美術探究会",
    year: 2025,
  },
  {
    id: 85,
    title: "中国の秦始皇帝と万里の長城",
    content: "秦始皇帝は中国統一を果たし、万里の長城を築いた。始皇帝陵や兵馬俑も有名。中国史の転換点となった人物。",
    category: "history",
    tags: ["china", "qin", "greatwall"],
    author: "世界史研究会",
    year: 2025,
  },
  {
    id: 86,
    title: "インドのガンジーと非暴力運動",
    content: "マハトマ・ガンジーはインド独立運動の指導者。非暴力・不服従の理念でイギリスからの独立を達成した。",
    category: "history",
    tags: ["india", "gandhi", "independence"],
    author: "世界史研究会",
    year: 2025,
  },
  {
    id: 87,
    title: "アラビアのロレンスと第一次世界大戦",
    content: "T.E.ロレンスは第一次世界大戦中、アラブ反乱を指導したイギリス人。映画『アラビアのロレンス』でも有名。",
    category: "history",
    tags: ["lawrence", "arabia", "ww1"],
    author: "世界史研究会",
    year: 2025,
  },
  {
    id: 88,
    title: "アマゾン川の流域と生物多様性",
    content: "アマゾン川は南米最大の河川。流域には多様な動植物が生息し、世界の生物多様性の宝庫とされる。",
    category: "nature",
    tags: ["amazon", "river", "biodiversity"],
    author: "自然探究会",
    year: 2025,
  },
  {
    id: 89,
    title: "イギリスの産業革命と社会変化",
    content: "18世紀後半、イギリスで始まった産業革命は、蒸気機関や工場制生産の普及で社会構造を大きく変えた。",
    category: "history",
    tags: ["uk", "industrial", "revolution"],
    author: "世界史研究会",
    year: 2025,
  },
  {
    id: 90,
    title: "アメリカのIT企業とシリコンバレー",
    content:
      "シリコンバレーはアメリカ・カリフォルニア州のIT企業集積地。Apple、Google、Facebookなど世界的企業が誕生した。",
    category: "tech",
    tags: ["usa", "siliconvalley", "it"],
    author: "IT百科編集部",
    year: 2025,
  },
  {
    id: 91,
    title: "アフリカのナイル川と古代文明",
    content: "ナイル川はアフリカ最長の河川。古代エジプト文明の発展に不可欠な存在で、農業や交通の要でもあった。",
    category: "history",
    tags: ["nile", "egypt", "civilization"],
    author: "世界史研究会",
    year: 2025,
  },
  {
    id: 92,
    title: "ロシアのバレエと芸術文化",
    content:
      "ロシアはバレエの本場。ボリショイ劇場やマリインスキー劇場、チャイコフスキーの音楽など、芸術文化が世界的に評価されている。",
    category: "art",
    tags: ["russia", "ballet", "culture"],
    author: "美術探究会",
    year: 2025,
  },
  {
    id: 93,
    title: "アメリカの宇宙開発とNASA",
    content: "NASAはアメリカの宇宙開発機関。アポロ計画やスペースシャトル、火星探査など、宇宙科学の最前線を担う。",
    category: "science",
    tags: ["usa", "nasa", "space"],
    author: "宇宙研究会",
    year: 2025,
  },
  {
    id: 94,
    title: "イギリスの王室と現代社会",
    content:
      "イギリス王室は伝統と現代性が融合した存在。エリザベス2世やチャールズ3世、王室行事や社会への影響について紹介。",
    category: "culture",
    tags: ["uk", "royal", "society"],
    author: "ヨーロッパ紀行編集部",
    year: 2025,
  },
  {
    id: 95,
    title: "アジアの仏教と宗教文化",
    content: "仏教はインド発祥で、アジア各地に広がった宗教。日本・中国・タイなどで独自の発展を遂げ、文化や思想に影響。",
    category: "culture",
    tags: ["asia", "buddhism", "religion"],
    author: "民族学会",
    year: 2025,
  },
  {
    id: 96,
    title: "アメリカのハリウッド映画産業",
    content: "ハリウッドは世界最大の映画産業拠点。多様なジャンルの映画が制作され、世界中に影響を与えている。",
    category: "entertainment",
    tags: ["usa", "hollywood", "movie"],
    author: "映画百科編集部",
    year: 2025,
  },
  {
    id: 97,
    title: "イギリスの紅茶文化とアフタヌーンティー",
    content: "イギリスでは紅茶が国民的飲み物。アフタヌーンティーの習慣や、ティールーム文化、紅茶の種類について紹介。",
    category: "culture",
    tags: ["uk", "tea", "afternoon"],
    author: "ヨーロッパ紀行編集部",
    year: 2025,
  },
  {
    id: 98,
    title: "アフリカのサファリ観光と自然保護",
    content: "アフリカではサファリ観光が盛ん。野生動物の保護と観光業の両立、現地コミュニティへの影響について解説。",
    category: "nature",
    tags: ["africa", "safari", "tourism"],
    author: "自然探究会",
    year: 2025,
  },
  {
    id: 99,
    title: "アジアの漢字文化圏と言語の歴史",
    content: "漢字は中国発祥で、日本・韓国・ベトナムなどに広がった。言語・文字・文化の交流と変遷について紹介。",
    category: "culture",
    tags: ["asia", "kanji", "language"],
    author: "民族学会",
    year: 2025,
  },
  {
    id: 100,
    title: "アメリカのジャズ音楽と文化",
    content: "ジャズはアメリカ南部で誕生した音楽ジャンル。即興演奏やブルースの影響、世界的な広がりについて解説。",
    category: "music",
    tags: ["usa", "jazz", "music"],
    author: "音楽探究会",
    year: 2025,
  },
];
